### ISSUE TITLE
Application error when linking to Sage hotbar

### ISSUE THREAD

**Issue by ThatsSoTrinda** [bdejesus/xiv-bars#79]
**Describe the bug**
[This](https://i.imgur.com/dwBFKcJ.png) is reported in the Chrome console when trying to use [this](https://xivbars.bejezus.com/job/SGE?s1=3922,3928,3935,3915,3926,0,0,0,3912,r7571,r7561,3904,3907,3902,3906,r7568,3911,3934,3913,3917,3919,r7559,0,r7562,3900,3914,3921,3901,3920,0,3903,3916,3927,3918,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0&l=1) link generated by the app.

The chrome extension references appear to be the extension DelugeSiphon, and I would doubt are related.

**To Reproduce**
1. Make a sage build using Hotbars
2. Click "Copy URL"
3. Attempt to view copied URL

**Expected behavior**
The action bars to load as intended.

**Screenshots**
Already provided above

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 64bit
 - Browser: Chrome 
 - Version: Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by bdejesus** [comment]
The version of data for the Sage and Reaper jobs were stubbed in prior to the official Endwalker client release. Because of this some features were expected _not_ to work until Job/Actions data became available from the live FFXIV game client. 

This is now fixed for new generated URLs, but not for URLs generated using the previous app release. Existing URLs generated using the previous app release version will not work.
